######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 1 19:14:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += Lab05.cpp widget.cpp
