######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 29 20:14:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += final.cpp widget.cpp
